### ISSUE TITLE
Fishing place

### ISSUE THREAD

**Issue by kwyes** [DamienShahan/LostArkFishingBot#4]
i dont think the exclamation mark img works.

is there any specific place i need to do fishing?

**Comment by DamienShahan** [comment]
What is your screen resolution? 
The fishing bot currently supports resolutions with a height of 1080p, 1440p and 2160p (that includes ultra wide monitors).

I would suggest fishing at East Luterra -> Wavestrand Port.
![image](https://user-images.githubusercontent.com/22813288/158251293-58e40762-2abd-4cee-b29a-b980476221b2.png)

Some users have reported issues fishing in Punika since the water is so bright. The bot seems to have issues "seeing" the exclamation point when contrast between it and the water is so low. When I have time, I will work on improving that.

**Comment by kwyes** [comment]
Hi I tried at east luttera . its working fine. Great.

I tried at Fantasm island and punika. its not working. i think its too bright probably. the program cant recognize the img.

**Comment by DamienShahan** [comment]
Currently I am having success fishing in Punika -> Starsand Beach, since it is much darker there. 

![image](https://user-images.githubusercontent.com/22813288/158258635-6937508f-9aab-480c-9e91-9346e88c3353.png)
